<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="mentorpi">

  <!-- Import Gazebo plugins -->
  <xacro:include filename="$(find mentorpi_description)/urdf/mentorpi.gazebo" />

  <!-- Constants -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <!-- Robot properties -->
  <xacro:property name="base_mass" value="2.5" /> <!-- kg -->
  <xacro:property name="base_width" value="0.31" />
  <xacro:property name="base_length" value="0.42" />
  <xacro:property name="base_height" value="0.18" />

  <!-- Wheel properties -->
  <xacro:property name="wheel_mass" value="0.5" /> <!-- kg -->
  <xacro:property name="wheel_radius" value="0.0508" /> <!-- 50.8mm -->
  <xacro:property name="wheel_width" value="0.026" /> <!-- 26mm -->
  
  <!-- Mecanum wheel offset -->
  <xacro:property name="wheel_separation_x" value="0.194" /> <!-- 194mm between front/rear -->
  <xacro:property name="wheel_separation_y" value="0.169" /> <!-- 169mm between left/right -->

  <!-- Inertial macros -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
             iyy="${m*(x*x+z*z)/12}" iyz="0" izz="${m*(x*x+y*y)/12}" />
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
             iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}" />
  </xacro:macro>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 1.0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <xacro:box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </inertial>
  </link>

  <!-- Base Footprint -->
  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius + 0.01}" rpy="0 0 0"/>
  </joint>

  <!-- Mecanum Wheels -->
  <xacro:macro name="mecanum_wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="dark_grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_reflect*wheel_separation_x/2} ${y_reflect*wheel_separation_y/2} ${-base_height/2}" 
              rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Create all four mecanum wheels -->
  <xacro:mecanum_wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:mecanum_wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:mecanum_wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
  <xacro:mecanum_wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>

  <!-- LIDAR Mount -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <xacro:cylinder_inertia m="0.2" r="0.05" h="0.08"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.0 0.0 ${base_height/2 + 0.04}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Gimbal Base -->
  <link name="camera_gimbal_base">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.04"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.08 0.08 0.04"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <xacro:box_inertia m="0.1" x="0.08" y="0.08" z="0.04"/>
    </inertial>
  </link>

  <joint name="camera_gimbal_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_gimbal_base"/>
    <origin xyz="${base_length/2 - 0.05} 0.0 ${base_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Gimbal Pan -->
  <link name="camera_gimbal_pan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.03"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.03"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <xacro:box_inertia m="0.05" x="0.06" y="0.06" z="0.03"/>
    </inertial>
  </link>

  <joint name="camera_gimbal_pan_joint" type="revolute">
    <parent link="camera_gimbal_base"/>
    <child link="camera_gimbal_pan"/>
    <origin xyz="0 0 0.035" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>

  <!-- Camera Gimbal Tilt -->
  <link name="camera_gimbal_tilt">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.08 0.03"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.08 0.03"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <xacro:box_inertia m="0.05" x="0.05" y="0.08" z="0.03"/>
    </inertial>
  </link>

  <joint name="camera_gimbal_tilt_joint" type="revolute">
    <parent link="camera_gimbal_pan"/>
    <child link="camera_gimbal_tilt"/>
    <origin xyz="0 0 0.03" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.785" upper="0.785" effort="10" velocity="1.0"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.06 0.03"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.2 0.2 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.06 0.03"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.02"/>
      <xacro:box_inertia m="0.02" x="0.03" y="0.06" z="0.03"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="camera_gimbal_tilt"/>
    <child link="camera_link"/>
    <origin xyz="0.04 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Camera Optical Frame -->
  <link name="camera_optical_link"/>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_link"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
  </joint>

  <!-- IMU -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="green">
        <color rgba="0.2 1.0 0.2 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <xacro:box_inertia m="0.001" x="0.02" y="0.02" z="0.01"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
